# Generated by Django 5.2.9 on 2026-02-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminstration", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="disciplinerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipline_records",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="adminstration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="adminstration.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_assignments",
                to="adminstration.section",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="adminstration.subject",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={
                ("teacher", "subject", "school_class", "section", "academic_year")
            },
        ),
    ]
