# Generated by Django 5.2.9 on 2026-02-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminstration", "0002_initial"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "teacher"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="adminstration.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="adminstration.section",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="adminstration.term",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="adminstration.subject",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="timetable.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="timetable.timetable",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("school_class", "section", "academic_year", "term"),
                name="unique_timetable_per_section_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("timetable", "time_slot"), name="unique_entry_per_timeslot"
            ),
        ),
    ]
