# Generated by Django 5.2.9 on 2026-02-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="students.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("exam", "student")},
        ),
    ]
