# Generated by Django 5.2.9 on 2026-02-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminstration", "0002_initial"),
        ("finance", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "accountant"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recorded_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "accountant"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="recorded_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "accountant"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_payments",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_payments",
                to="adminstration.term",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="adminstration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="adminstration.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="finance.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="adminstration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "accountant"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="adminstration.term",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="finance.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="feestructure",
            constraint=models.UniqueConstraint(
                fields=("name", "school_class", "academic_year"),
                name="unique_fee_structure_per_class_year",
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["student", "fee_structure"],
                name="finance_fee_student_922e33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["status", "payment_date"], name="finance_fee_status_833b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "academic_year", "term"],
                name="finance_inv_student_e1438b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="finance_inv_status_0e2dc8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceitem",
            unique_together={("invoice", "fee_structure")},
        ),
    ]
