# Generated by Django 5.2.9 on 2026-02-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminstration", "0002_initial"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="academic_year",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="adminstration.academicyear",
            ),
        ),
    ]
