# Generated by Django 5.2.9 on 2026-02-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminstration", "0002_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "hr"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["teacher", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["admin", "hr"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="adminstration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["admin", "hr"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="adminstration.term",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="staff.department",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role__in": ["teacher", "accountant", "hr", "admin"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["department", "is_active"],
                name="staff_staff_departm_298423_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["user", "is_active"], name="staff_staff_user_id_037e41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["academic_year", "term"], name="staff_payro_academi_9b058c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["status", "payment_date"], name="staff_payro_status_a468c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("staff", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["staff", "status"], name="staff_leave_staff_i_a0b57a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["start_date", "end_date"], name="staff_leave_start_d_a172e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("staff", "date"), name="unique_attendance_per_staff_per_day"
            ),
        ),
    ]
